use_frameworks!

target 'DataTableKit_Example' do
  pod 'DataTableKit', :path => '../'

  target 'DataTableKit_Tests' do
    inherit! :search_paths

  
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
